name: general
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - tqdm
  # For ipython and jupyter lab
  - ipykernel
  - ipywidgets
  - flake8
  - black
  - pip
  - pip:
    - cupy-cuda101
    - tensorflow
    - pyfftw
    - clawpack
